/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package listFiles;

import org.junit.Test;

import java.io.FileNotFoundException;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() throws FileNotFoundException {
        App classUnderTest = new App();
        assertNotNull("Home dir should exists", classUnderTest.listNonDotFiles());
        assertNotNull("Home dir should exists", classUnderTest.listDotFiles());
    }
}
