/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package averagePrice;

import java.util.ArrayList;
import java.util.Scanner;

public class App {

    private static ArrayList<Double> getPrices() {
        ArrayList<Double> prices = new ArrayList<>();

        boolean added = true;
        while ( added ) {
            String price = getUserInput("Enter next price and press enter, leave empty to calculate the average price: " );
            added = !price.isEmpty();

            if ( added ) {
                try {
                    prices.add( Double.valueOf( price ) );
                } catch ( NumberFormatException e ) {
                    System.err.println( "Invalid number formatting..." );
                }
            }
        }

        return prices;
    }

    private static String getUserInput(String header) {
        System.out.println( header );
        return (new Scanner(System.in)).nextLine();
    }

    public static void main(String[] args) {
        ArrayList<Double> prices = getPrices();
        priceCalculation calculation = new priceCalculation(prices);

        System.out.println("Total:");
        System.out.println( calculation.total );

        System.out.println("Quantity:");
        System.out.println( calculation.quantity );

        System.out.println("Average:");
        System.out.println( calculation.average );

    }

    private static class priceCalculation {

        public int quantity;
        public double total;
        public double average;

        public priceCalculation ( ArrayList<Double> prices ) {
            this.quantity = prices.size();
            this.total = prices
                    .stream()
                    .mapToDouble(Double::doubleValue)
                    .sum();
            this.average = this.total / this.quantity;
        }

    }
}
